### ISSUE TITLE
Memory & Webhook

### ISSUE THREAD

**Issue by mirdhyn** [veino/logfan#12]
Could you please explain how to use `memory` & `webhook` attributes - and what are they supposed to do, please? Thank you!

**Comment by vjeantet** [comment]
Memory

The intent : 
Provide a mechanism to share data through processors.

The memory allows processors to share data.

I planned to allow veino to run on multiple hosts/instances to distribute load.
Scenario :
- Start logfan(veino) on host1
	- logfan starts processors, doing its jobs...
- Start veino on host2 with a reference to host1
	- veino2 announce itself to veino1 and get processors graph and configuration.
	- veino1 add virtual workers from veino2 to each processor pool.
(A lot challenge here, some processors may not be distributable, like a lot of inputs)


In this scenario processors should be allowed to share data across network. 

Processors do not have to handle network, concurrency, distribution and persistence.

Interface Memory is there to ease this.

Tomorrow we could change memory implementation to use a Redis / bolt or anything else, without drawbacks for processors.

Some memory usages : throttle events, remenber the last time a specific event was found, caching, etc...

I'm open to any comment on this idea, its implementation :)

**Comment by vjeantet** [comment]
Webhooks

WebHook allows an agent (a named and configured pool of worker's processors) to communicate with external http protocol.

A external app, script could request some information or pass a new information to change the processor behaviour.

Each agent, on start, has to register a hook httpHandle func.

Veino handles the httpServer and routing requests to agents

**Comment by vjeantet** [comment]
A good scenario for Memory : a change detection processor that monitor a certain field and match if that field changes.

A good scenario for WebHooks : a blacklist processor that checks a certain field against a blacklist, and match if it is in the blacklist.
* Use WebHooks to populate the liste while the logfan is running...
