### ISSUE TITLE
Unable to pass a hash with multiple keys

### ISSUE THREAD

**Issue by mirdhyn** [veino/logfan#3]
Consider the following config file:
```
input {
  stdin {}
}
filter {
  mutate {
    add_field => {"one" => 1, "two" => 2}
  }
}
output {
  stdout {}
}
```
Starting logfan outputs following error message:
```
2016/07/13 09:57:17 ParseHash parse error unexpected token ',' expected one of LSTokenComment|LSTokenIdentifier|LSTokenRCurlyBrace|LSTokenString on line 7 col 28
```

**Comment by vjeantet** [comment]
I Will Check this today thanks for reporting

**Comment by mirdhyn** [comment]
Actually hashes inside plugin configuration must be like hashes of the configuration itself: without commas.

Following configs are working:
```ruby
filter {
  mutate {
    add_field => {
      "one" => 1
      "two" => 2
    }
  }
}
```
or even
```ruby
filter {
  mutate {
    add_field => { "one" => 1 "two" => 2  }
  }
}
```
I guess adding an optional comma for all the hashes would make it less confusing.
