### ISSUE TITLE
config parser whitespace sensitive

### ISSUE THREAD

**Issue by pbkdf3** [veino/logfan#7]
First, this is a great project, thank you!  I noticed a small config parser issue.  I often test with -e directly on command line and don't add extra whitespace, so this came up the first time I tried running logfan and took me a bit of puzzling to figure out. 

Only difference between below 2 configs is the extra space prior to right curly at end of input section:

     [root@devbox logfan]# ./logfan -e 'input { stdin {} } output { stdout { codec => rubydebug } }'
     2016/08/03 07:38:40 ready
     ^C
     2016/08/03 07:38:41 stopping...
     2016/08/03 07:38:45 Everything stopped gracefully. Goodbye!
     
     [root@devbox logfan]# ./logfan -e 'input { stdin {}} output { stdout { codec => rubydebug } }'
     2016/08/03 07:38:49 ERROR while using config  Setting 1 parse error unexpected token '{' expected 'LSTokenAssignment' on line 1 col 34

**Comment by vjeantet** [comment]
good catch i'll address it ! thanks

**Comment by vjeantet** [comment]
fixed in 63244a642faf9937b54874b67a64a43daab7e86a
